Update new_release script.
- The directory in which to store APT repositories is now configurable.
- Improve error handling.
- Clean up child processes when killed.
- Give each APT repository update a date-based version number.

diff --git a/new_release b/new_release
--- a/new_release
+++ b/new_release
@@ -1,108 +1,62 @@
 #!/bin/bash
+# Builds packages for Phusion Passenger and Nginx.
+
 set -e
 
-BASE_DIR=`dirname "$0"`
-BASE_DIR=`cd "$BASE_DIR"; pwd`
 
-GIT_URL="$1"
-REPO_DIR="$2"
-APT_DIR="$3"
-REF=${4:-origin/master}
-DEFAULT_NAMESPACE=`basename "$REPO_DIR" | sed -E 's/\..*?$//'`
-NAMESPACE=${DEFAULT_NAMESPACE:-default}
-source config/general
-source lib/bashlib
-export WORK_DIR="/var/cache/passenger_apt_automation/$NAMESPACE"
-export PKG_DIR="$WORK_DIR/pkg"
-export PBUILDFOLDER="$WORK_DIR/pbuilder"
+##### Parse parameters #####
 
-if [[ "$GIT_URL" = "" || "$REPO_DIR" = "" || "$APT_DIR" = "" ]]; then
-	echo "Usage: ./new_release GIT_URL REPO_DIR APT_DIR [REF]"
+export GIT_URL="$1"
+export PROJECT_NAME="$2"
+export REF=${3:-origin/master}
+
+if [[ "$GIT_URL" = "" || "$PROJECT_NAME" = "" ]]; then
+	echo "Usage: ./new_release GIT_URL PROJECT_NAME [REF]"
+	exit 1
+fi
+if [[ "$PROJECT_NAME" != passenger && "$PROJECT_NAME" != passenger-enterprise ]]; then
+	echo "Error: the PROJECT_NAME parameter must be either 'passenger' or 'passenger-enterprise'"
 	exit 1
 fi
 
+
+##### Initialization #####
+
+export BASE_DIR=`dirname "$0"`
+export BASE_DIR=`cd "$BASE_DIR"; pwd`
+source "$BASE_DIR/lib/bashlib"
+
+load_general_config
+use_dummy_gpg
+require_running_as_psg_apt_automation_user
+
+export WORK_DIR="/var/cache/passenger_apt_automation/$PROJECT_NAME.workdir"
+export PKG_DIR="$WORK_DIR/pkg"
+export PBUILDFOLDER="$WORK_DIR/pbuilder"
+
+export PROJECT_GIT_REPO_DIR="/var/cache/passenger_apt_automation/$PROJECT_NAME.git"
+export PROJECT_APT_REPO_DIR="$APT_REPO_DIR/$PROJECT_NAME.apt"
+
+unset CCACHE
+
+shopt -s dotglob
+
 echo "# Initializing..."
-rm -rf "$WORK_DIR"
 mkdir -p "$WORK_DIR"
+echo -n > "$WORK_DIR/stage"
+echo $$ > "$WORK_DIR/pid"
 
-(
-	set -x
-	mkdir -p "$PKG_DIR"
-	mkdir -p "$PBUILDFOLDER"
-	echo $$ > "$WORK_DIR/pid"
-	ln -s ~/pbuilder/*.tgz "$PBUILDFOLDER"/
-	unset USE_CCACHE
-	trap "stage Error error; exit 1" ERR
 
-	if [[ -e "$REPO_DIR" ]]; then
-		stage "Updating repository..." updating_repo
-		cd "$REPO_DIR"
-		if [[ "`git config remote.origin.url`" != "$GIT_URL" ]]; then
-			echo "Git repository URL does not match!"
-			exit 1
-		fi
-		git fetch
-		rm -rf *
-	else
-		stage "Cloning repository..."
-		git clone "$GIT_URL" "$REPO_DIR"
-		cd "$REPO_DIR"
-	fi
-	git reset --hard "$REF"
+##### Run main program #####
 
-	stage "Building Phusion Passenger source packages..." building_passenger_source_packages
-	drake debian:source_packages
+set -o pipefail
 
-	stage "Building Phusion Passenger binary packages..." building_passenger_binary_packages
-	drake debian:binary_packages -j$CONCURRENCY_LEVEL
+trap "stage Error error; exit 1" ERR
+stage "Obtaining lock..." obtaining_lock
 
-	stage "Building Nginx source packages..." building_nginx_source_packages
-	cd "$BASE_DIR"
-	export PASSENGER_DIR="$REPO_DIR"
-	./create_nginx_package source_packages
-	stage "Building Nginx binary packages..." building_nginx_binary_packages
-	./create_nginx_package binary_packages -j$CONCURRENCY_LEVEL
+chpst -l /var/cache/passenger_apt_automation/lock \
+	bash internal/new_release.sh 2>&1 | \
+	gawk '{ print strftime("%Y-%m-%d %H:%M:%S  "), $0; fflush(); }' | \
+	tee "$WORK_DIR/full.log"
 
-	stage "Signing packages..." signing_packages
-	cd "$BASE_DIR"
-	export PATH="$BASE_DIR/lib/dummygpg:$PATH"
-	debsign -k$SIGNING_KEY $PKG_DIR/nginx*.changes
-	debsign -k$SIGNING_KEY $PKG_DIR/official/*.changes
-	debsign -k$SIGNING_KEY $PBUILDFOLDER/*_result/*.changes
-
-	stage "Importing packages into APT repository..." importing_packages
-	rm -rf "$APT_DIR.tmp" "$APT_DIR.old" "$APT_DIR.bak2"
-	cp -dpR "$APT_DIR" "$APT_DIR.tmp"
-
-	cd "$APT_DIR.tmp"
-	for DIST in $DEBIAN_DISTROS; do
-		for ARCH in $DEBIAN_ARCHS; do
-			if [[ $ARCH == amd64 ]]; then
-				pbase_name="$DIST"
-			else
-				pbase_name="$DIST-$ARCH"
-			fi
-			result_dir="$PBUILDFOLDER/${pbase_name}_result"
-			reprepro --keepunusednewfiles --keepunreferencedfiles -Vb . includedeb $DIST $result_dir/*_$ARCH.deb
-		done
-		reprepro --keepunusednewfiles --keepunreferencedfiles -Vb . includedeb $DIST $PBUILDFOLDER/${DIST}_result/*_all.deb
-		for F in $PBUILDFOLDER/${DIST}_result/*.dsc; do
-			reprepro --keepunusednewfiles --keepunreferencedfiles -Vb . includedsc $DIST $F
-		done
-	done
-	../sign_repo "`pwd`"
-	cd ..
-
-	if [[ -e "$APT_DIR.bak" ]]; then
-		mv "$APT_DIR.bak" "$APT_DIR.bak2"
-	fi
-	cp -dpR "$APT_DIR" "$APT_DIR.bak"
-	rm -rf "$APT_DIR.bak2"
-
-	mv "$APT_DIR" "$APT_DIR.old"
-	mv "$APT_DIR.tmp" "$APT_DIR"
-	rm -rf "$APT_DIR.old"
-
-	stage "Done" done
-) 2>&1 | awk '{ print strftime("%Y-%m-%d %H:%M:%S -- "), $0; fflush(); }' | tee "$WORK_DIR/full.log"
-test ${PIPESTATUS[0]} -eq 0
+stage "Done" done
