create nginx-dev package for jammy and bullseye

diff --git a/shell b/shell
--- a/shell
+++ b/shell
@@ -10,6 +10,7 @@ source "$SELFDIR/internal/lib/distro_info.sh"
 
 WORK_DIR=
 CACHE_DIR=
+PASSENGER_DIR=
 DISTRIBUTIONS="$DEFAULT_DISTROS"
 ARCHITECTURES="amd64 arm64"
 
@@ -19,6 +20,7 @@ function usage()
 	echo "Open a shell in a build box container."
 	echo
 	echo "Required options:"
+	echo "  -p DIR     Path to passenger directory"
 	echo "  -c DIR     Path to cache directory"
 	echo
 	echo "Optional options:"
@@ -36,8 +38,11 @@ function parse_options()
 {
 	local OPTIND=1
 	local opt
-	while getopts "c:w:d:a:h" opt; do
+	while getopts "p:c:w:d:a:h" opt; do
 		case "$opt" in
+		p)
+			PASSENGER_DIR="$OPTARG"
+			;;
 		c)
 			CACHE_DIR="$OPTARG"
 			;;
@@ -67,6 +72,10 @@ function parse_options()
 		echo "ERROR: please specify a cache directory with -c."
 		exit 1
 	fi
+        if [[ "$PASSENGER_DIR" = "" ]]; then
+		echo "ERROR: please specify a passenger directory with -p."
+		exit 1
+	fi
 }
 
 parse_options "$@"
@@ -76,6 +85,19 @@ CACHE_DIR=$(absolute_path "$CACHE_DIR")
 run mkdir -p "$CACHE_DIR"
 run mkdir -p "$CACHE_DIR/pbuilder/ccache"
 BUILDBOX_IMAGE=$(get_buildbox_image)
+
+DISTRO_NGINXS=()
+for distro in $DISTRIBUTIONS; do
+    export DOCKER_CLI_EXPERIMENTAL=enabled
+    if docker manifest inspect "debian:$distro" >/dev/null 2>&1; then
+        kind="debian"
+    else
+        kind="ubuntu"
+    fi
+    echo "+ Getting $distro latest nginx version"
+    version=$(docker run "$kind:$distro" bash -c 'apt-get update >/dev/null && apt-cache policy nginx-core' | awk '/Candidate:/{print $NF}')
+    DISTRO_NGINXS+=("$distro:$version")
+done
 
 if [[ "$WORK_DIR" != "" ]]; then
 	WORK_DIR=$(absolute_path "$WORK_DIR")
@@ -92,7 +114,7 @@ verbose_run docker run \
 	-e "ARCHITECTURES=$ARCHITECTURES" \
 	-e "APP_UID=$(/usr/bin/id -u)" \
 	-e "APP_GID=$(/usr/bin/id -g)" \
-	$BUILDBOX_IMAGE \
+	"$BUILDBOX_IMAGE" \
 	/system/internal/scripts/inituidgid.sh \
 	/system/internal/scripts/initccache.sh
 
@@ -101,6 +123,7 @@ exec docker run \
 	--rm -t -i \
 	--privileged \
 	-v "$SELFDIR:/system:ro" \
+	-v "$PASSENGER_DIR:/passenger" \
 	-v "$CACHE_DIR:/cache" \
 	-v "$CACHE_DIR/pbuilder:/var/cache/pbuilder" \
 	-e "DISTRIBUTIONS=$DISTRIBUTIONS" \
@@ -108,8 +131,9 @@ exec docker run \
 	-e "APP_UID=$(/usr/bin/id -u)" \
 	-e "APP_GID=$(/usr/bin/id -g)" \
 	-e "LC_CTYPE=C.UTF-8" \
+	-e "DISTRO_NGINXS=${DISTRO_NGINXS[*]}" \
 	"${DOCKER_OPTIONS[@]}" \
-	$BUILDBOX_IMAGE \
+	"$BUILDBOX_IMAGE" \
 	/sbin/my_init --quiet --skip-runit --skip-startup-files -- \
 	/system/internal/scripts/inituidgid.sh \
 	/system/internal/shell/preinit.sh \
